### PR TITLE
Fix Show Movie button checked state

### PR DESCRIPTION
**Pull request by pcjco**
Fix issue : Checking "Show Movie" is doing nothing

### CODE REVIEW

**Comment by ozankaraali** [comment]
Thanks, I forgot that, hopefully this time it works, could you check the whole functionality if you can, I had no access to VOD services.

**Comment by ozankaraali** [comment]
Update is live at https://github.com/ozankaraali/QiTV/releases/tag/v1.4.7
I will mark as release after we ensure things are correct.

**Comment by pcjco** [comment]
> Thanks, I forgot that, hopefully this time it works, could you check the whole functionality if you can, I had no access to VOD services.

Yes it works.
But practically but it is not usable. Usual number of items per page on VOD services are 14 with total numbers that could reach 10.000 titles. Time spent on the requests loop is hours. And storing all the json data returned for every title make the config.json very big. Exploration using a limited scope (with a max number of title each time) and with a Next/Previous command to continue the browsing seems a better way. Adding a way to only retrieve content with a filter like a category, genre, country, year or specified search terms would also help, if API allow that.

**Comment by ozankaraali** [comment]
> > Thanks, I forgot that, hopefully this time it works, could you check the whole functionality if you can, I had no access to VOD services.
> 
> Yes it works. But practically but it is not usable. Usual number of items per page on VOD services are 14 with total numbers that could reach 10.000 titles. Time spent on the requests loop is hours. And storing all the json data returned for every title make the config.json very big. Exploration using a limited scope (with a max number of title each time) and with a Next/Previous command to continue the browsing seems a better way. Adding a way to only retrieve content with a filter like a category, genre, country, year or specified search terms would also help, if API allow that.

I can imagine, maybe still it can live in prerelease like nightly build for the users really want it, I believe there should be a faster way but currently I don’t have any stb account, so I just wanted to give credits to the people who wanted to contribute, I should discover the vod api some time later but basically since channels can be requested with either pagination like how the other opensourced stb players doing or like what I do in this software, get_all_channels. Probably there should be get_all_vods or similar, or at worst, we can run threaded requests etc later.

**Comment by ozankaraali** [comment]
I have no account to test, so can any of you try to load channels and videos to see if this works at all? The aim of this version is I tried to introduce async loading, especially for the vod movies, it should load without freezing, a bit faster.
@pcjco @Amined9 
https://github.com/ozankaraali/QiTV/releases/tag/v1.4.8

**Pull request merged**
