### PR TITLE
Reorganization of content loading and providers management + Showing Movie/Serie info on selected applicable item

### PR DESCRIPTION
**Pull request by pcjco**
- Enhanced the `ChannelList` UI to show info when selecting an STB vod or serie.
- Restructured `OptionsDialog` in `options.py` to include tabs for settings and providers, with new fields and buttons for managing provider settings. Adding settings for checking updates and showing content info.
- Allow to give a user-friendly name to each provider (if no name given, use URL as name by default)
- Added new signals to `VideoPlayer` to show/hide media controls in main panel.
- M3U source handle 'group-title' (group-title value shown in content tree as first column).
- M3U export 'group-title', 'tvg-logo' and 'tvg-id'
- Centralized provider-related operations through a new `provider_manager` in `channel_list.py`, improving code organization and maintainability.
- Introduced `SetProviderThread` class for improved responsiveness during initialization or change of provider.
- Added `ContentLoader` class in `content_loader.py` for asynchronous content loading.
- Updated `ConfigManager` in `config_manager.py` and added new default options. Added new properties for configuration options.
- `ProviderContext` and `ProviderManager` classes in `provider_manager.py` for managing provider configurations and interactions.
- Adding tzlocal  module as required new dependency. Used to know the local zone name (for example Europe/Paris) to use in STB cookie. Needed to have a correct EPG info from STB requests in future.

### CODE REVIEW

**Comment by ozankaraali** [comment]
Wow, too much stuff, thanks! @pcjco 

I am really busy this month but when I have time I will review and merge hopefully.
Thanks again for your contributions!

**Comment by pcjco** [comment]
No problem.
In a next PR, i should be able to add some support for EPG but as it was going to make too much changes i wanted to make an intermediate PR.
image

**Comment by ozankaraali** [comment]
Not gonna lie, this looks really nice!

One reminder is that while doing these changes please make sure that the functionality of M3U/Xtream list views and play functionality are not affected (probably not affected but still these features are generally overlooked while we design this app focused on STB).

I will be looking forward to receive that PR as well! 🥳

**Comment by ozankaraali** [comment]
Hi @pcjco I merged this to dev to test and merge into main, I see couple of important issues in a glance, 

- the search in m3u list does not work as intended, then I created a pr from your epg stuff to see if you fixed, which is way too complicated to update on top of that.
- Also verify_url is missing (a small detail I can fix, but the functionality is affected it seems)

I believe we must be solving the issues before we can merge further, I will be trying more about that later, but if you want to fix them, you're welcome and thank you for your support with this app.

**Pull request merged**
