### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ozankaraali**
https://github.com/ozankaraali/QiTV/commit/58e68cb598f7376bdb2685b9e1a78cb381ebd338
 versioning by string,
 provider context initialization?,
  indentation? also why we have param remove?
  why do we disconnect more than once?
  prehook tzlocal
  why do we have duplicate definitions in channel_list:
  channel_list.py:962: error: Name "can_show_content_info" already defined on line 599  [no-redef]
channel_list.py:969: error: Name "create_content_info_panel" already defined on line 617  [no-redef]
channel_list.py:974: error: Name "setup_movie_tvshow_content_info" already defined on line 622  [no-redef]
channel_list.py:985: error: Name "clear_content_info_panel" already defined on line 661  [no-redef]
channel_list.py:1007: error: Name "clear_layout" already defined on line 698  [no-redef]
channel_list.py:1016: error: Name "switch_content_info_panel" already defined on line 708  [no-redef]
channel_list.py:1034: error: Name "populate_movie_tvshow_content_info" already defined on line 893  [no-redef]
channel_list.py:1059: error: Name "show_favorite_layout" already defined on line 956  [no-redef]

### CODE REVIEW

**Comment by ozankaraali** [comment]
Hi @pcjco,
I have reviewed dev channel update that we fetched from your epg branch, first of all, again, thank you for the contribution, I managed to run the software with a bunch of changes.

However, there are still some issues I need to clarify:
provider context initialization in provider_manager.py was unclear.
In content_loader.py, some params needed some indentation to work and it seems it's working now but just to be clear, can you check if any param was deleted when compared to your version?
in def display_content(self, items, content_type="content", select_first=True), why do you call disconnect twice?
channel_list.py:962: error: Name "can_show_content_info" already defined on line 599 [no-redef]
channel_list.py:969: error: Name "create_content_info_panel" already defined on line 617 [no-redef]
channel_list.py:974: error: Name "setup_movie_tvshow_content_info" already defined on line 622 [no-redef]
channel_list.py:985: error: Name "clear_content_info_panel" already defined on line 661 [no-redef]
channel_list.py:1007: error: Name "clear_layout" already defined on line 698 [no-redef]
channel_list.py:1016: error: Name "switch_content_info_panel" already defined on line 708 [no-redef]
channel_list.py:1034: error: Name "populate_movie_tvshow_content_info" already defined on line 893 [no-redef]
channel_list.py:1059: error: Name "show_favorite_layout" already defined on line 956 [no-redef]
can you select the which are the correct redefinitions, since all the definitions are different than each other.

Thank you, and best regards,
Ozan

**Comment by pcjco** [comment]
Hi, I just added a commit with few corrections on this PR.
I removed the duplicated methods also to keep the correct ones.

**Comment by ozankaraali** [comment]
Thank you for the help @pcjco . I added them to dev to refer this PR, I am still busy, but I will review them and let you know about that once I am free.

**Comment by ozankaraali** [comment]
Hi @pcjco
Would you explain
 
https://github.com/ozankaraali/QiTV/blob/b9e65236e3064b23927380891f22c4d938737bab/provider_manager.py#L115C13-L144C83

Why do we have these code here? Some providers do not just report anything but they work without id. What is the origin of that?

**Comment by pcjco** [comment]
It was a tentative to filter "blocked" providers which answer to handshake but won't return any content afterwards (and it shows that your provider has blocked your account on the device).
A common behavior seems to return those empty ID/NAME when asking profile. But it might not be the best way and maybe not blocked providers could be falsely filtered here...

**Comment by ozankaraali** [comment]
Thanks @pcjco, I will revert this part in the next patch but I would like to thank you again for the EPG stuff.

Meanwhile, I think EPG info sometimes handled different than other players, where the others show info, in this one, we cannot fetch, or timing issues may happen, any idea? If not, don’t worry, I will check what’s going on later.

**Pull request merged**
