### PR TITLE
Movies window

### PR DESCRIPTION
**Pull request by Amined9**

### CODE REVIEW

**Comment by ozankaraali** [comment]
Thanks I will check and approve when I have time

**Comment by ozankaraali** [comment]
Okay so I believe this is ready:
https://github.com/ozankaraali/QiTV/releases/tag/v1.4.6

I don't have access to a VOD server, please check and give me a feedback so I can mark this as latest, or if it does not work we can work on that.

Best,
Ozan

**Comment by Amined9** [comment]
Hi,

The latest version works well. But when you want to update the movie list, the application freeze because of the amount of requests. for me, getting around 40000 movies takes 10 minutes. as @pcjco says, it's better to do categories of movies that can be clickable to have a small list of movie, and this logic can be applied to the series category.

PS : how i can dm you to discuss about STB account ?

**Comment by ozankaraali** [comment]
Hi, @Amined9 
Glad to hear, at least it works to some extent. I believe we even don’t need categories, we need a faster indexing. Recently I have been busy and I haven’t used vod functionality but sure, when I have time, I can think about it. 
For dms, you can reach me via telegram or email, whatever you prefer.
Best,
Ozan

**Comment by Amined9** [comment]
Yes, categories are not necessary for movies. but if we have a serie group, a categories logic need to be added due to multiple seasons and episodes. for the loading of the movie list, maybe a spinner animation can be added.
so, where can i find your email or telegram.

**Comment by ozankaraali** [comment]
You can find me by my name ozankaraali and ozankaraali at gmail.

**Pull request merged**
